name: Python MNIST Model

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Pretraining Model Check
      run: |
        python pre_test.py
    
    - name: Train and save model
      run: |
        python mnist_model.py
    
    - name: Test saved model
      run: |
        python test_saved_model.py
    
    - name: Run advanced tests
      run: |
        python advanced.py